config/routes.rb
Rails.application.routes.draw do
  get 'books' => "books#index",as: 'index_book'
  post 'books' => "books#create"
  get 'books/:id' => "books#show", as: 'book'
  get 'books/:id/edit' => "books#edit", as: 'edit_book'
  patch 'books/:id' => "books#update", as: 'update_book'
  get root :to => "homes#top"
  delete 'books/:id' => "books#destroy", as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @book = Book.new

    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = 'Book was successfully destroyed'
      redirect_to index_book_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "show", book_path %>
<%= link_to "back", index_book_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <th>title</th>
    <th>body</th>
    <th colspan="3"></th>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", book_path(book.id), method: :delete, data: { confirm: "Are You Sure?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>New Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post, local: true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h2>title:</h2>
<p><%= @book.title %></p>

<h2>body:</h2>
<p><%= @book.body %></p>

<%= link_to "edit", edit_book_path %>
<%= link_to "back", index_book_path %>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<%= link_to "start", index_book_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:p, value, class: key) %>
    <% end %>
    <%= yield %>
  </body>
</html>